# Ch?y nhi?u task cùng lúc
org.gradle.parallel=true

# Gi? Gradle luôn ? tr?ng thái ch?, không ph?i kh?i ??ng l?i
org.gradle.daemon=true

# Ch? build nh?ng gì thay ??i (Incremental build)
org.gradle.caching=true

## Gi?i h?n RAM ?? không làm lag c? Windows và IntelliJ
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m